---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    flux.weave.works/automated: "true"
  name: web
  namespace: dev
spec:
  template:
    spec:
      $setElementOrder/containers:
      - name: nginx
      containers:
      - image: nginx:1.18-alpine-perl
        name: nginx
