apiVersion: v1
kind: Service
metadata:
  labels:
    app: web
  name: ng-svc
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30007
  selector:
    app: web
  type: NodePort
